services:
  product-service:
    image: product-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - checkoutsy-network

networks:
  checkoutsy-network:
    external: true
