server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://product-db:5432/product
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      springframework:
        web: DEBUG


