services:
  product-db:
    image: postgres:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: product-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - product_data:/var/lib/postgresql/data
    networks:
      - checkoutsy-network

volumes:
  product_data:

networks:
  checkoutsy-network:
    external: true
